mc:
  size: 19693568
  object_id: ee03c259-4ab4-4049-551f-40eae117557f
  sha: sha256:3e8b2439546d60a7b7ec68500da7d0515119cbd18e73b79af00bf9b0638178e5
minio:
  size: 58798080
  object_id: f0a2a9ae-3e91-4401-7894-ca789556e6bc
  sha: sha256:6c82293c417ed0e9fbbd5bccc134fb27340ebd6c61b7a43dbe02a248ab4400ee
minio-license-verify:
  size: 3776326
  object_id: 203dff91-39e5-4ce9-6c2f-5aace80e25e1
  sha: sha256:76f84164091f7a9ced4f010f2b3e31102e05d1ca064c8cdd45db9252ed6a1b45
